<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4CPQ9V6" failures="1" tests="3" name="Test" time="0.082" errors="0" timestamp="15 Mar 2020 10:23:44 GMT">
  <testcase classname="continuous.demo" name="Test1" time="0.008"/>
  <testcase classname="continuous.demo" name="Test2" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at continuous.demo.Test2(demo.java:52)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="continuous.demo" name="Test3" time="0.001"/>
</testsuite> <!-- Test -->
